go-linux-amd64.tar.gz:
  size: 102601309
  sha: 6a00c39435edc1e102f1fb75cc1137fba4c9e4e2
go-version.txt:
  size: 63
  sha: d9f376822765b3c5903ae8e1227090d98af34948
spacebears_src.tgz:
  size: 2830438
  sha: 3d9cd05f686d0c4a819889957d3308c259105942
